### ISSUE TITLE
Let documark compile return file

### ISSUE THREAD

**Issue by MalcolmK** [mauvm/documark#15]
Hey!

Do you think it would be possible to let the command `$ documark compile` return the file's name that was generated. This way I can automate my process of compiling the document and have the possibility to do additional stuff with the file, because I have the name returned.

Malcolm

**Comment by mauvm** [comment]
I have recently removed the `documark config` command, which outputted the document's configuration. But this is a good use case to add it again. Then you could do something like `documark compile && documark config | jq '.file'` (http://stedolan.github.io/jq/).

**Comment by mauvm** [comment]
I have added `documark config` to v0.5.2+. So you can now do: `documark compile && documark.config | jq '.file' -r`.

**Comment by MalcolmK** [comment]
I think you mean `documark compile && documark config | jq '.file' -r` ?

**Comment by mauvm** [comment]
Oops, typo. Yes!
